import { FlatCompat } from '@eslint/eslintrc'
import { dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'coverage/**',
      'next-env.d.ts', // auto-generated by Next.js itself, not ours to lint
      // Captured third-party pages, scripts and datasets kept as evidence. They are recorded
      // exactly as fetched, so their style is not ours to correct.
      'data/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Server actions bound via `.bind(null, id)` (e.g. publish/delete) must keep `formData`
      // in their signature even when the body doesn't read it — underscore-prefixed is the
      // project's convention for "intentionally unused".
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
]

export default eslintConfig
