import { FlatCompat } from '@eslint/eslintrc'
import { dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'coverage/**',
      'next-env.d.ts', // auto-generated by Next.js itself, not ours to lint
      // Captured third-party pages, scripts and datasets kept as evidence. They are recorded
      // exactly as fetched, so their style is not ours to correct.
      'data/**',
      // The Python environment the corpus scripts run in (docs/specs/revamp-2026-09.md). It is
      // gitignored, and it ships a vendored Playwright driver whose bundled JavaScript is not ours
      // to lint; without this, `npm run lint` reports two thousand errors in someone else's code.
      '.venv*/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Server actions bound via `.bind(null, id)` (e.g. publish/delete) must keep `formData`
      // in their signature even when the body doesn't read it — underscore-prefixed is the
      // project's convention for "intentionally unused".
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // The corpus document (step 6.1). `/d/*` and `/h/*` are served as plain HTML with no client
    // router and no React Server Components stream, so both of these rules describe a page this
    // code is deliberately not: `<Link>` needs the router these documents do not load, and
    // `next/head` belongs to a page whose `<head>` Next.js writes. Here the document writes its
    // own head and its links are ordinary navigations. Every other file keeps both rules.
    files: [
      'components/document/**/*.tsx',
      'components/dossier/corpus/**/*.tsx',
      'components/dossier/v3/**/*.tsx',
      'lib/dossier-v3/document.tsx',
      'components/hubs/**/*.tsx',
      'lib/corpus/document.tsx',
      'lib/document/**/*.tsx',
      'lib/hubs/document.tsx',
    ],
    rules: {
      '@next/next/no-html-link-for-pages': 'off',
      '@next/next/no-head-element': 'off',
    },
  },
]

export default eslintConfig
