import 'dotenv/config'
import { execFileSync } from 'node:child_process'
import { createReadStream, existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline'
import { join } from 'node:path'

import { normalizeContentName, normalizeIdentityName } from '@/lib/background/name-normalization'

/**
 * Builds the searchable-name index: every name printed on a published label, mapped to the medicine
 * it should find.
 *
 * The site aggregates one record per active moiety, which is right for the record and wrong for
 * search. A moiety record is filed under "levothyroxine", so a reader typing "levothyroxine sodium"
 * — the name printed on 280 published labels and on the box in their hand — finds nothing. Measured
 * against the label archive, 78% of brand names and 77% of generic names returned nothing before
 * this index existed.
 *
 * The alias machinery to fix it was already there: `searchDrugs` joins `drug_aliases`, and
 * `scripts/ingest/aliases.ts` writes a hand-curated list of roughly sixty international spellings.
 * What was missing is that the list is tiny next to the archive, and that only the full ingest
 * populates it — a seeded database has none at all, which is why search worked in some environments
 * and not others. This index ships with the dataset instead, so the names exist wherever the data
 * does.
 *
 * What it does NOT do: invent names. Every alias here is a string a manufacturer printed on a label
 * that openFDA published, and it maps to a medicine only when that label is about one substance and
 * that substance already has a record. A name whose product is a combination resolves to nothing
 * until that product has a page, and is reported rather than pointed somewhere approximate.
 *
 * Usage:
 *   tsx scripts/background/build-name-index.ts <labelIndex.ndjson>
 */

interface IndexedLabel {
  setId: string
  declaredSubstanceCount?: number
  brandNames: string[]
  genericNames: string[]
  substanceNames?: string[]
}

const normalizeIdentity = normalizeIdentityName
const normalizeMoiety = normalizeContentName

/** Alias kinds the schema accepts. */
type AliasKind = 'brand' | 'salt_form' | 'common_name'

export interface NameIndexEntry {
  alias: string
  kind: AliasKind
}

/**
 * Aliases kept per medicine. Some moieties appear on thousands of labels under near-identical
 * marketing names, and past a point another spelling of the same package adds nothing a reader
 * would type. Set high rather than tight: every dropped alias is a name that returns nothing, which
 * is the failure this index exists to remove. The number dropped is reported so the cap is visible.
 */
const MAX_ALIASES_PER_MEDICINE = 250

/**
 * Whether a printed name is worth indexing.
 *
 * Labels carry marketing strings that are really package descriptions — "0.025% Capsaicin Pain
 * Relief Patch 4ct". Indexing them is not harmful but it buries the names people actually type, so
 * a name must carry a real word and must not read as a dosage line.
 */
function isSearchableName(name: string): boolean {
  const trimmed = name.trim()
  if (trimmed.length < 3 || trimmed.length > 300) return false
  const words = normalizeIdentity(trimmed).split(' ').filter(Boolean)
  if (words.length === 0 || words.length > 12) return false
  // At least one word that is not a number, a unit, or a single letter.
  const substantive = words.filter(
    (word) =>
      word.length >= 3 && !/^\d+$/u.test(word) && !/^(?:mg|ml|mcg|ct|oz|gm|iu|kg|lb)$/u.test(word),
  )
  if (substantive.length === 0) return false
  // A name that opens with a quantity is a package description rather than a name.
  return !/^\d/u.test(trimmed)
}

interface MedicineRow {
  slug: string
  name: string
}

function loadMedicineRows(): MedicineRow[] {
  const dir = join(process.cwd(), 'data', 'drugs')
  const rows: MedicineRow[] = []
  for (const file of readdirSync(dir)
    .filter((name) => name.endsWith('.ndjson'))
    .sort()) {
    for (const line of readFileSync(join(dir, file), 'utf8').split('\n')) {
      if (!line.trim()) continue
      const record = JSON.parse(line) as { id?: string; name?: string }
      if (record.id && record.name) rows.push({ slug: record.id, name: record.name })
    }
  }
  return rows
}

function serialize(index: Record<string, NameIndexEntry[]>): string {
  const entries = Object.keys(index)
    .sort()
    .map((slug) => `  ${JSON.stringify(slug)}: ${JSON.stringify(index[slug])},`)
    .join('\n')
  return `// Generated by scripts/background/build-name-index.ts — do not edit by hand.
//
// Every name a manufacturer printed on a published label, mapped to the medicine a reader typing it
// should find. Nothing here is invented: an alias is a string that appears on a label openFDA
// published, and it maps to a medicine only when that label is about one substance.

export interface NameIndexEntry {
  alias: string
  kind: 'brand' | 'salt_form' | 'common_name'
}

export const MEDICINE_NAME_INDEX: Record<string, NameIndexEntry[]> = {
${entries}
}
`
}

async function main() {
  const [indexPath] = process.argv.slice(2).filter((value) => !value.startsWith('--'))
  if (!indexPath || !existsSync(indexPath)) {
    console.error('Usage: tsx scripts/background/build-name-index.ts <labelIndex.ndjson>')
    process.exit(1)
  }

  const rows = loadMedicineRows()
  // A medicine is reachable by its exact recorded name and by its moiety, so a record filed under
  // the base name still claims the salt spellings printed on labels for it.
  const byIdentity = new Map<string, string>()
  const byMoiety = new Map<string, string>()
  const ownNames = new Set<string>()
  for (const row of rows) {
    const identity = normalizeIdentity(row.name)
    const moiety = normalizeMoiety(row.name)
    if (identity.length >= 3 && !byIdentity.has(identity)) byIdentity.set(identity, row.slug)
    if (moiety.length >= 3 && !byMoiety.has(moiety)) byMoiety.set(moiety, row.slug)
    ownNames.add(identity)
  }
  console.log(`[names] ${rows.length} medicine rows · ${byIdentity.size} identities`)

  const collected = new Map<string, Map<string, { alias: string; kind: AliasKind }>>()
  const stats = {
    labelsRead: 0,
    labelsAboutOneSubstance: 0,
    namesSeen: 0,
    namesRejectedAsPackageText: 0,
    namesWithNoMedicine: 0,
    combinationNamesSkipped: 0,
  }

  const reader = createInterface({
    input: createReadStream(indexPath, { encoding: 'utf8' }),
    crlfDelay: Infinity,
  })

  for await (const line of reader) {
    if (!line.trim()) continue
    const label = JSON.parse(line) as IndexedLabel
    stats.labelsRead += 1

    // A combination's names belong to the combination, and pointing them at one of its ingredients
    // would send a reader searching for a two-drug product to a page about half of it.
    if (label.declaredSubstanceCount !== 1) {
      stats.combinationNamesSkipped += 1
      continue
    }
    stats.labelsAboutOneSubstance += 1

    const substance = (label.substanceNames ?? label.genericNames)[0]
    if (!substance) continue
    const slug =
      byIdentity.get(normalizeIdentity(substance)) ?? byMoiety.get(normalizeMoiety(substance))
    if (!slug) {
      stats.namesWithNoMedicine += 1
      continue
    }

    const forMedicine = collected.get(slug) ?? new Map<string, { alias: string; kind: AliasKind }>()
    const add = (name: string, kind: AliasKind) => {
      stats.namesSeen += 1
      if (!isSearchableName(name)) {
        stats.namesRejectedAsPackageText += 1
        return
      }
      const key = name.trim()
      // The medicine's own name is not an alias for itself.
      const identity = normalizeIdentity(key)
      if (ownNames.has(identity) && byIdentity.get(identity) === slug) return
      // Deduplicated case-insensitively, because the unique index is on lower(alias): storing
      // "Childrens Tylenol", "Childrens TYLENOL" and "CHILDRENS TYLENOL" spends three slots of the
      // per-medicine budget to insert one row.
      const caseKey = key.toLowerCase()
      if (!forMedicine.has(caseKey)) forMedicine.set(caseKey, { alias: key, kind })
    }

    for (const brand of label.brandNames) add(brand, 'brand')
    for (const generic of label.genericNames) add(generic, 'salt_form')
    for (const name of label.substanceNames ?? []) add(name, 'salt_form')
    collected.set(slug, forMedicine)
  }

  const index: Record<string, NameIndexEntry[]> = {}
  let kept = 0
  let dropped = 0
  for (const [slug, aliases] of collected) {
    /**
     * How likely a name is to be the one a reader types.
     *
     * A brand outranks a salt spelling, because the moiety record already answers to its own
     * moiety. Within a kind, a name carrying a strength or pack size ranks last: "Acetaminophen
     * 325 MG" is a package description, and 250 of those would fill the budget and push the brand
     * a reader actually types out of it.
     */
    const typedFirst = (entry: { alias: string; kind: AliasKind }): number =>
      (/\d/u.test(entry.alias) ? 2 : 0) + (entry.kind === 'brand' ? 0 : 1)
    const ordered = [...aliases.values()].sort(
      (left, right) =>
        typedFirst(left) - typedFirst(right) ||
        left.alias.split(' ').length - right.alias.split(' ').length ||
        left.alias.localeCompare(right.alias),
    )
    if (ordered.length > MAX_ALIASES_PER_MEDICINE)
      dropped += ordered.length - MAX_ALIASES_PER_MEDICINE
    const capped = ordered.slice(0, MAX_ALIASES_PER_MEDICINE)
    if (capped.length === 0) continue
    index[slug] = capped
    kept += capped.length
  }

  const outPath = join(
    process.cwd(),
    'scripts',
    'seed-data',
    'background',
    'name-index.generated.ts',
  )
  writeFileSync(outPath, serialize(index))
  execFileSync('npx', ['prettier', '--write', outPath], { stdio: 'ignore' })

  console.log(`[names] ${JSON.stringify(stats)}`)
  console.log(
    `[names] ${kept} aliases across ${Object.keys(index).length} medicines · ${dropped} beyond the per-medicine cap of ${MAX_ALIASES_PER_MEDICINE}`,
  )
  console.log(`[names] wrote ${outPath}`)
}

void main().catch((error) => {
  console.error(error)
  process.exit(1)
})
