import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import {
  MOLECULAR_PROPERTIES_VERSION,
  type MolecularPropertiesBySlug,
  type MolecularPropertyRecord,
} from '@/lib/background/molecular-properties'
import { RECORDED_BACKGROUND } from '../seed-data/background'

/**
 * Builds (or refreshes) the molecular-properties dataset entirely by machine.
 *
 * For every recorded medicine that carries a PubChem CID in its `registryIdentifiers`, this
 * fetches PubChem's computed descriptors and writes them to
 * `scripts/seed-data/background/molecular-properties.generated.ts`. Nothing here is authored:
 * the CID comes from the already-verified background record, and every value comes straight from
 * the service. Re-running is the refresh — a changed descriptor simply lands in the regenerated
 * file, and `git diff` is the change report.
 *
 * Usage:
 *   tsx scripts/background/build-molecular-properties.ts            # fetch and write
 *   tsx scripts/background/build-molecular-properties.ts --check    # fetch and report drift only
 */

const PROPERTY_FIELDS = [
  'MolecularFormula',
  'MolecularWeight',
  'XLogP',
  'HBondDonorCount',
  'HBondAcceptorCount',
  'RotatableBondCount',
  'TPSA',
  'HeavyAtomCount',
  'Complexity',
  'CanonicalSMILES',
  'InChIKey',
].join(',')

interface PubChemProperties {
  CID?: number
  MolecularFormula?: string
  MolecularWeight?: string | number
  XLogP?: number
  HBondDonorCount?: number
  HBondAcceptorCount?: number
  RotatableBondCount?: number
  TPSA?: number
  HeavyAtomCount?: number
  Complexity?: number
  CanonicalSMILES?: string
  ConnectivitySMILES?: string
  InChIKey?: string
}

function numberOrUndefined(value: string | number | undefined): number | undefined {
  if (typeof value === 'number') return Number.isFinite(value) ? value : undefined
  if (typeof value === 'string') {
    const parsed = Number(value)
    return Number.isFinite(parsed) ? parsed : undefined
  }
  return undefined
}

async function fetchProperties(cid: string): Promise<PubChemProperties | null> {
  try {
    const response = await fetch(
      `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${encodeURIComponent(cid)}/property/${PROPERTY_FIELDS}/JSON`,
      { signal: AbortSignal.timeout(20000) },
    )
    if (!response.ok) return null
    const payload = (await response.json()) as {
      PropertyTable?: { Properties?: PubChemProperties[] }
    }
    return payload.PropertyTable?.Properties?.[0] ?? null
  } catch {
    return null
  }
}

function toRecord(
  cid: string,
  retrievedAt: string,
  properties: PubChemProperties,
): MolecularPropertyRecord {
  const record: MolecularPropertyRecord = {
    version: MOLECULAR_PROPERTIES_VERSION,
    cid,
    retrievedAt,
  }
  const assign = <K extends keyof MolecularPropertyRecord>(
    key: K,
    value: MolecularPropertyRecord[K] | undefined,
  ) => {
    if (value !== undefined) record[key] = value
  }
  assign('molecularFormula', properties.MolecularFormula)
  assign('molecularWeight', numberOrUndefined(properties.MolecularWeight))
  assign('xLogP', numberOrUndefined(properties.XLogP))
  assign('hBondDonorCount', numberOrUndefined(properties.HBondDonorCount))
  assign('hBondAcceptorCount', numberOrUndefined(properties.HBondAcceptorCount))
  assign('rotatableBondCount', numberOrUndefined(properties.RotatableBondCount))
  assign('tpsa', numberOrUndefined(properties.TPSA))
  assign('heavyAtomCount', numberOrUndefined(properties.HeavyAtomCount))
  assign('complexity', numberOrUndefined(properties.Complexity))
  // PubChem renamed this field; accept either spelling and store one canonical key.
  assign('smiles', properties.CanonicalSMILES ?? properties.ConnectivitySMILES)
  assign('inchiKey', properties.InChIKey)
  return record
}

function serialize(dataset: MolecularPropertiesBySlug): string {
  const slugs = Object.keys(dataset).sort()
  const entries = slugs
    .map(
      (slug) =>
        `  ${JSON.stringify(slug)}: ${JSON.stringify(dataset[slug], null, 2).replace(/\n/gu, '\n  ')},`,
    )
    .join('\n')
  return `// Generated by scripts/background/build-molecular-properties.ts — do not edit by hand.
//
// Every value is fetched from PubChem's computed-property service, keyed by the CID already
// recorded in that medicine's registryIdentifiers. Nothing here is authored; re-run the script to
// refresh, and let \`git diff\` report what changed.

import type { MolecularPropertiesBySlug } from '@/lib/background/molecular-properties'

export const MOLECULAR_PROPERTIES: MolecularPropertiesBySlug = {
${entries}
}
`
}

async function main() {
  const checkOnly = process.argv.includes('--check')
  const retrievedAt = new Date().toISOString().slice(0, 10)
  const withCid = Object.entries(RECORDED_BACKGROUND).flatMap(([slug, background]) => {
    const cid = background.registryIdentifiers?.pubchemCid
    return cid ? [{ slug, cid }] : []
  })

  const dataset: MolecularPropertiesBySlug = {}
  const failures: string[] = []
  for (const { slug, cid } of withCid) {
    const properties = await fetchProperties(cid)
    if (!properties) {
      failures.push(`${slug} (CID ${cid})`)
    } else {
      dataset[slug] = toRecord(cid, retrievedAt, properties)
    }
    await new Promise((resolve) => setTimeout(resolve, 220))
  }

  console.log(
    `[molecular] ${JSON.stringify({
      medicinesWithCid: withCid.length,
      fetched: Object.keys(dataset).length,
      failed: failures.length,
    })}`,
  )
  for (const failure of failures) console.warn(`[molecular.unreachable] ${failure}`)

  if (checkOnly) {
    process.exit(failures.length > 0 ? 1 : 0)
  }

  const outPath = join(
    process.cwd(),
    'scripts',
    'seed-data',
    'background',
    'molecular-properties.generated.ts',
  )
  writeFileSync(outPath, serialize(dataset))
  console.log(`[molecular] wrote ${Object.keys(dataset).length} record(s) to ${outPath}`)
  process.exit(0)
}

void main().catch((error) => {
  console.error(error)
  process.exit(1)
})
