export const ENTITY_CLASSES = [
  'APPROVED_MEDICINE',
  'APPROVED_BIOLOGIC',
  'INVESTIGATIONAL_MEDICINE',
  'OFF_LABEL_OR_COMPOUNDED',
  'WITHDRAWN_MEDICINE',
  'CONTROLLED_NO_APPROVED_USE',
  'COMBINATION_PRODUCT',
  'BOTANICAL_OR_ORGANISM_PREPARATION',
  'SUPPLEMENT_INGREDIENT',
  'MARKETED_PRODUCT_INGREDIENT',
  'REGISTRY_ONLY_IDENTITY',
  'PLACEHOLDER',
] as const
export type EntityClass = (typeof ENTITY_CLASSES)[number]
