import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * What organism each medicine row is, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-biological-identity.ts` from the NCBI Taxonomy dump.
 * Absent is empty rather than fatal, so a checkout that has not run the builders still runs its
 * tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'biological-identity.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const BIOLOGICAL_IDENTITY_BACKGROUND = read()
