import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * Ingredient breakdowns for corpus rows that are themselves combination products, read from JSON at
 * runtime.
 *
 * Generated by `scripts/background/build-combination-row-composition.ts`. Absent is empty rather
 * than fatal, so a checkout that has not run the builders still runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(
        join(process.cwd(), 'data', 'registries', 'combination-row-composition.json'),
        'utf8',
      ),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const COMBINATION_ROW_COMPOSITION = read()
