import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * Chemical identity for corpus rows no label source reaches, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-compound-identity-background.ts`. Empty rather than fatal
 * when it has not been generated, so a fresh checkout still runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(
        join(process.cwd(), 'data', 'registries', 'compound-identity-background.json'),
        'utf8',
      ),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const COMPOUND_IDENTITY_BACKGROUND = read()
