import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * What the deterministic label extractor found for rows the curated corpus already covers, read
 * from JSON at runtime.
 *
 * Each value holds only modules the curated envelope leaves absent, so it can add to a curated
 * record and can never replace part of one. Generated by
 * `scripts/background/build-curated-gap-extraction.ts`. Absent is empty rather than fatal, so a
 * checkout that has not run the builders still runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(
        join(process.cwd(), 'data', 'registries', 'curated-gap-extraction.json'),
        'utf8',
      ),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const CURATED_GAP_EXTRACTION = read()
