import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * Where each medicine appears in the published drug-label archive, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-label-presence.ts`. Kept out of TypeScript for the same
 * reason the other registries are: large, regenerated wholesale, read only by scripts and tests.
 *
 * An absent file is empty rather than fatal, so a checkout that has not run the builders still runs
 * its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'label-presence.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const LABEL_PRESENCE_BACKGROUND = read()
