import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * What the National Drug Code directory lists for each substance, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-product-listing.ts`. Absent is empty rather than fatal, so
 * a checkout that has not run the builders still runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'product-listing.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const PRODUCT_LISTING_BACKGROUND = read()
