import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * When each substance was first approved, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-regulatory-approval.ts` from the Drugs@FDA register.
 * Absent is empty rather than fatal, so a checkout that has not run the builders still runs its
 * tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'regulatory-approval.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const REGULATORY_APPROVAL_BACKGROUND = read()
