import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * What kind of material each substance is, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-source-material.ts` from FDA's substance registry. Absent
 * is empty rather than fatal, so a checkout that has not run the builders still runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'source-material.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const SOURCE_MATERIAL_BACKGROUND = read()
