import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * Records built from the substance registry for medicine rows the extraction pipeline left empty.
 *
 * Generated by `scripts/background/build-substance-backed-background.ts`. Read from JSON for the
 * same reason the registries are, and empty rather than fatal when it has not been generated.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(
        join(process.cwd(), 'data', 'registries', 'substance-backed-background.json'),
        'utf8',
      ),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const SUBSTANCE_BACKED_BACKGROUND = read()
