import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * How the supplement label database files each ingredient, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-supplement-ingredient.ts` from the database's own
 * vocabulary. Absent is empty rather than fatal, so a checkout that has not run the builders still
 * runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'supplement-ingredient.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const SUPPLEMENT_INGREDIENT_BACKGROUND = read()
