import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { MedicineRecordedBackground } from '@/lib/background/types'

/**
 * Recorded background for supplement rows, read from JSON at runtime.
 *
 * Generated by `scripts/background/build-supplement-background.ts` from the NIH supplement label
 * database. Kept out of TypeScript for the same reason the other registries are: it is large,
 * regenerated wholesale, and read only by scripts and tests.
 *
 * An absent file is empty rather than fatal, so a checkout that has not run the builders still
 * runs its tests.
 */
function read(): Record<string, MedicineRecordedBackground> {
  try {
    return JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'registries', 'supplement-background.json'), 'utf8'),
    ) as Record<string, MedicineRecordedBackground>
  } catch {
    return {}
  }
}

export const SUPPLEMENT_BACKGROUND = read()
